In [1]:
import tensorflow as tf
import numpy as np

In [3]:
x = tf.Variable(initial_value=[[1,2],[3,4]],shape=(2,2),dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [6]:
c = tf.constant(value = [1,2,3,4], dtype=tf.float32, shape=(2,2))
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [7]:
x + c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 4.],
       [6., 8.]], dtype=float32)>

In [8]:
x + 1


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [9]:
x.numpy() + c


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 4.],
       [6., 8.]], dtype=float32)>

In [10]:
x.numpy() + c.numpy()

array([[2., 4.],
       [6., 8.]], dtype=float32)

In [11]:
x.assign_add(c)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[2., 4.],
       [6., 8.]], dtype=float32)>

In [12]:
numpyArray = np.ones(shape = (2,2))

In [13]:
x + numpyArray

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 5.],
       [7., 9.]], dtype=float32)>

In [14]:
xReshaped = tf.reshape(x,(1,4))

In [16]:
xReshaped + np.reshape(numpyArray, newshape=(4,1))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[3., 5., 7., 9.],
       [3., 5., 7., 9.],
       [3., 5., 7., 9.],
       [3., 5., 7., 9.]], dtype=float32)>

In [17]:
tf.cast(x, dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [26]:
with tf.GradientTape(persistent = True) as tape:
  tape.watch(xReshaped)
  y = x * x
  z = np.reshape(numpyArray, newshape=(4,1)) * xReshaped
tape.gradient(y,x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.,  8.],
       [12., 16.]], dtype=float32)>

In [27]:
tape.gradient(z,xReshaped)

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[4., 4., 4., 4.]], dtype=float32)>

In [28]:
del tape

In [30]:
with tf.GradientTape(persistent= True) as tape1:
  with tf.GradientTape(persistent= True) as tape2:
    y = x * x
  dyDx = tape2.gradient(y,x)
dy2Dx2 = tape1.gradient(dyDx, x)

In [31]:
dyDx

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.,  8.],
       [12., 16.]], dtype=float32)>

In [32]:
dy2Dx2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>